package com.ugar.databasecrud.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.util.Set;

@DynamoDBTable(tableName = "users")
@NoArgsConstructor@AllArgsConstructor@Data
public class User {

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    private String user_id;
    @DynamoDBAttribute(attributeName = "user_password")
    private String user_password;
    @DynamoDBAttribute(attributeName = "user_name")
    private String user_name;
    @DynamoDBAttribute(attributeName = "roleIds")
    private Set<String> roleIds;


}
